const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const path = require('node:path');
const src = fs.readFileSync(path.join(__dirname, '../prototype-src.js'), 'utf8');
// Load only the pure helpers and model/schema validation, without a browser DOM.
const helpers = src.slice(0,src.indexOf('function renderFilters()'));
const validate = src.slice(src.indexOf('function validateImport('),src.indexOf('async function exportBackup()'));
const ctx = { console, setTimeout, clearTimeout, URLSearchParams, location: {search: ''} };
const api = vm.runInNewContext(helpers+'\n'+validate+'\n({parseFreq,matches,validateImport,escapeHtml,demoData,labels})',ctx);
assert.equal(api.parseFreq('2.4G'),2400);
assert.equal(api.parseFreq('2400000khz'),2400);
assert.equal(api.parseFreq('1575,42'),1575.42);
assert.equal(api.parseFreq('nonsense'),null);
assert.equal(api.matches(api.demoData.find(d=>d.id==='wifi'),'2450'),true);
assert.equal(api.matches(api.demoData.find(d=>d.id==='wifi'),'OFDM 2.4 GHz'),true);
assert.equal(api.matches(api.demoData.find(d=>d.id==='bt'),'OFDM'),false);
assert.equal(api.escapeHtml('<img src=x onerror="x">'),'&lt;img src=x onerror=&quot;x&quot;&gt;');
const candidate={id:'a',entityId:'obj',entity:'Test',band:'Band 1',cat:'other',a:100,b:200,tags:['test'],images:[]};
assert.equal(api.validateImport(candidate).band,'Band 1');
assert.throws(()=>api.validateImport({...candidate,a:300}),/діапазон/);
assert.throws(()=>api.validateImport({...candidate,cat:'unknown'}),/категорія/);
assert.throws(()=>api.validateImport({...candidate,images:[{dataUrl:'data:text/html;base64,WA=='}]}),/зображення/);
assert.deepEqual(Object.keys(api.labels).sort(),['bluetooth','cellular','gnss','other','uav','uhf','vhf','wifi'].sort());
console.log('PASS: parse frequency, keyword/frequency search, import validation, safe HTML escaping (11 assertions)');
