import type { FrequencyBand } from "./types";

// Demonstration records only. Replace or extend these with your own verified database.
export const demoBands: FrequencyBand[] = [
  {
    id: "airband-vhf",
    entityName: "Civil aviation voice",
    bandName: "VHF Airband",
    category: "vhf",
    startMHz: 118,
    endMHz: 137,
    purpose: "Voice / aviation communications",
    technology: "AM",
    description: "Example reference entry for the civil VHF aviation voice band.",
    tags: ["VHF", "aviation", "voice", "AM"],
    screenshotCount: 0,
  },
  {
    id: "ism-433",
    entityName: "Short-range devices",
    bandName: "433 MHz reference region",
    category: "uhf",
    startMHz: 433.05,
    endMHz: 434.79,
    purpose: "Short-range devices / telemetry examples",
    description: "Reference region commonly encountered in SDR observations. Regulatory use depends on jurisdiction.",
    tags: ["UHF", "SRD", "telemetry"],
    screenshotCount: 1,
  },
  {
    id: "example-uav-link",
    entityName: "Example UAV profile",
    bandName: "Demo control link",
    category: "uav",
    startMHz: 915,
    endMHz: 928,
    purpose: "Demo only — control / telemetry",
    technology: "Example record",
    description: "Fictitious demonstration band showing how a UAV-associated record can appear in the atlas.",
    tags: ["UAV", "control", "demo"],
    screenshotCount: 2,
  },
  {
    id: "wifi-24",
    entityName: "Wi‑Fi",
    bandName: "2.4 GHz",
    category: "wifi",
    startMHz: 2400,
    endMHz: 2483.5,
    purpose: "Wireless LAN",
    technology: "IEEE 802.11",
    description: "Reference entry for the 2.4 GHz Wi‑Fi/ISM region.",
    tags: ["Wi-Fi", "2.4 GHz", "OFDM", "DSSS"],
    screenshotCount: 3,
  },
  {
    id: "bluetooth-24",
    entityName: "Bluetooth",
    bandName: "2.4 GHz",
    category: "bluetooth",
    startMHz: 2402,
    endMHz: 2480,
    purpose: "Short-range data",
    technology: "Bluetooth Classic / LE",
    description: "Reference entry for Bluetooth operation in the 2.4 GHz ISM region.",
    tags: ["Bluetooth", "FHSS", "2.4 GHz"],
    screenshotCount: 2,
  },
  {
    id: "example-uav-video",
    entityName: "Example UAV profile",
    bandName: "Demo video link",
    category: "uav",
    startMHz: 5725,
    endMHz: 5850,
    purpose: "Demo only — video/data",
    technology: "Example record",
    description: "Fictitious record used to demonstrate that one object may have multiple separate frequency bands.",
    tags: ["UAV", "video", "demo"],
    screenshotCount: 1,
  },
];
